Terraform network

diff --git a/cloudbuild/cloudbuild-terraform-test-deploy.yaml b/cloudbuild/cloudbuild-terraform-test-deploy.yaml
--- a/cloudbuild/cloudbuild-terraform-test-deploy.yaml
+++ b/cloudbuild/cloudbuild-terraform-test-deploy.yaml
@@ -42,5 +42,22 @@ steps:
           /scripts/lock-build.sh $PROJECT_ID
           exit 0
 
+  - id: 'TF Apply (Previous Build)'
+    waitFor: ['Check for Build Locks']
+    name: "gcr.io/bj-terraform-cicd/$_IMAGE_NAME:stable"
+    entrypoint: 'sh'
+    args:
+      - '-c'
+      - |
+         set -e
+
+         cd /
+         cp /workspace/tf_sa.json /tf_sa.json
+         if ! /scripts/apply_network_tf_locally.sh $PROJECT_ID ; then
+           echo "Terraform Apply failed - aborting build"
+           /scripts/unlock-build $PROJECT_ID
+           exit 1
+         fi
+
 substitutions:
   _IMAGE_NAME: bj-cicd-terraform
