test1

diff --git a/cloudbuild/cloudbuild-terraform-test-deploy.yaml b/cloudbuild/cloudbuild-terraform-test-deploy.yaml
--- a/cloudbuild/cloudbuild-terraform-test-deploy.yaml
+++ b/cloudbuild/cloudbuild-terraform-test-deploy.yaml
@@ -55,10 +55,16 @@ steps:
          cp /workspace/tf_sa.json /tf_sa.json
          if ! /scripts/apply_network_tf_locally.sh $PROJECT_ID ; then
            echo "Terraform Apply failed - aborting build"
-           /scripts/unlock-build $PROJECT_ID
+           /scripts/unlock-build.sh $PROJECT_ID
            exit 1
          fi
 
+          if ! /scripts/apply_tf_locally.sh $PROJECT_ID ; then
+           echo "Terraform Apply failed - aborting build"
+           /scripts/unlock-build $PROJECT_ID
+           exit 1
+         fi
+         
 substitutions:
   _IMAGE_NAME: bj-cicd-terraform
 
